name: Image Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: nodeversion
        run: echo ::set-output name=NODE::$(cat .nvmrc)
      - uses: actions/cache@v1
        with:
          path: api/node_modules
          key: ${{ steps.nodeversion.outputs.NODE }}-node_modules-${{ hashFiles('api/yarn.lock') }}
          restore-keys: |
            ${{ steps.nodeversion.outputs.NODE }}-node_modules-
      - uses: actions/cache@v1
        with:
          path: ui/node_modules
          key: ${{ steps.nodeversion.outputs.NODE }}-node_modules-${{ hashFiles('ui/yarn.lock') }}
          restore-keys: |
            ${{ steps.nodeversion.outputs.NODE }}-node_modules-
      - name: Use Node.js ${{steps.nodeversion.outputs.NODE}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nodeversion.outputs.NODE }}
      - name: install API
        run: |
          cd api
          yarn
      - name: API lint
        run: |
          cd api
          yarn lint
      - name: API build
        run: |
          cd api
          yarn build
          cp package.json dist/package.json
          cp yarn.lock dist/yarn.lock
          cd dist
          yarn
      - name: install UI
        run: |
          cd ui
          yarn
      - name: UI lint
        run: |
          cd ui
          yarn lint
      - name: UI build
        run: |
          cd ui
          echo VUE_APP_REVISION=$GITHUB_SHA >> .env.production
          yarn build
      - name: docker build
        run: |
          docker build .
      - name: Push to registry
        if: github.ref == 'refs/heads/master'
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          dockerfile: Dockerfile
          name: zekth/too-much-artisans/api
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: "latest"
      - name: Push to server
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SRV_HOST }}
          username: ${{ secrets.SRV_USERNAME }}
          password: ${{ secrets.SRV_PASSWORD }}
          port: ${{ secrets.SRV_PORT }}
          script: |
            cd artisans
            docker-compose down
            docker-compose pull
            docker-compose up -d
            docker rmi -f $(docker images -f "dangling=true" -q) || true
