name: Base Image build

on:
  pull_request:
    paths:
      - .github/workflows/base_image_pr.yaml
      - Dockerfile_base

jobs:
  build:
    name: Build base image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: docker build
        run: docker build -f Dockerfile_base .
