name: Base Image build

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/base_image_push.yaml
      - Dockerfile_base

jobs:
  build:
    name: Build base image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to registry
        if: github.ref == 'refs/heads/master'
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          dockerfile: Dockerfile_base
          name: keycap-archivist/app/base
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: "latest"
